Repository ExtensionEngine/tailor, pull requests merged in 2018-03, with the labels that each got.

#16 Fixed issue with duplicated fields upon publish
  server/shared/publishing/helpers.js
Labels: enhancement

#8 As a User I should be able to clone Activity
  client/api/activity.js
  client/api/course.js
  client/assets/stylesheets/common/_buttons.scss
  client/components/common/ActivityBrowser/SelectActivity.vue
  client/components/common/ActivityBrowser/SelectRepository.vue
  client/components/common/ActivityBrowser/index.vue
  client/components/course/Activity.vue
  client/components/course/InsertActivity.vue
  client/components/course/InsertActivity/CreateActivity.vue
  client/components/course/InsertActivity/SelectAction.vue
  client/components/course/InsertActivity/index.vue
  client/store/helpers/collection.js
  client/store/modules/activities.js
  client/utils/activity.js
  config/shared/activities.js
  server/activity/activity.controller.js
  server/activity/activity.model.js
  server/activity/index.js
Labels: feature request

#9 Refactoring storage layer
  .env.example
  config/server/storage.js
  package-lock.json
  package.json
  server/shared/storage/index.js
  server/shared/storage/providers/amazon.js
  server/shared/storage/providers/filesystem.js
  server/shared/storage/validation.js
Labels: enhancement

#17 Default meta support
  README.md
  config/shared/activities.js
  server/activity/activity.controller.js
  server/course/course.controller.js
Labels: feature request

#19 Implement Brightcove video teaching element
  client/components/course/Revisions/EntityRevisions.vue
  client/components/editor/structure/AddElement/SelectElement.vue
  client/components/editor/teaching-elements/BrightcoveVideo/Player.vue
  client/components/editor/teaching-elements/BrightcoveVideo/index.vue
  client/components/editor/teaching-elements/index.vue
  client/components/editor/toolbar/BrightcoveVideoToolbar.vue
  client/components/editor/toolbar/index.vue
  server/shared/storage/helpers.js
Labels: :construction: work in progress, feature request

#13 Implement DatePicker component
  client/components/common/Meta/DatePicker.vue
  client/components/common/Meta/index.vue
  package-lock.json
  package.json
Labels: feature request

#29 Enable image embedding inside html
  client/components/editor/teaching-elements/Html/image-embed.js
  client/components/editor/teaching-elements/Html/image-embed.scss
  client/components/editor/teaching-elements/Html/index.vue
  client/components/editor/teaching-elements/Html/tooltip.js
  client/components/editor/toolbar/QuillToolbar.vue
Labels: feature request

#59 Awesome welcome message
  server/index.js
Labels: enhancement

#58 Server preflight script
  package-lock.json
  package.json
  server/script/preflight.js
Labels: enhancement
