Repository ExtensionEngine/tailor, pull requests merged in 2019-06, with the labels that each got.

#268 ESLint import sort
  .eslintrc.js
  client/App.vue
  client/api/resource.js
  client/components/catalog/Card/index.vue
  client/components/catalog/Container.vue
  client/components/common/ActivityBrowser/SelectActivity.vue
  client/components/common/Meta/DatePicker.vue
  client/components/content-elements/tce-drag-drop/edit/index.vue
  client/components/content-elements/tce-fill-blank/edit/index.vue
  client/components/content-elements/tce-html/edit/image-embed.js
  client/components/content-elements/tce-html/edit/index.vue
  client/components/content-elements/tce-matching-question/edit/index.vue
  client/components/content-elements/tce-numerical-response/edit/index.vue
  client/components/content-elements/tce-pdf/edit/index.vue
  client/components/content-elements/tce-single-choice/edit/index.vue
  client/components/course/Outline/InsertActivity/CreateActivity.vue
  client/components/course/Outline/InsertActivity/index.vue
  client/components/course/Outline/NoActivities.vue
  client/components/course/Revisions/RevisionItem.vue
  client/components/course/Revisions/index.vue
  client/components/course/Settings/CloneModal.vue
  client/components/course/Settings/General.vue
  client/components/course/Sidebar/Discussion/Thread.vue
  client/components/course/Sidebar/Header.vue
  client/components/course/TreeView/TreeGraph.vue
  client/components/course/TreeView/index.vue
  client/components/editor/index.vue
  client/components/editor/structure/AssessmentItem.vue
  client/components/editor/structure/ContentContainers/Container.vue
  client/components/editor/structure/Exams/AssessmentGroup.vue
  client/components/editor/structure/Exams/GroupIntroduction.vue
  client/components/editor/structure/Exams/index.vue
  client/main.js
  client/router.js
  client/store/helpers/collection.js
  client/store/index.js
  client/store/modules/activities.js
  client/store/modules/course.js
  client/utils/activity.js
Labels: :construction: work in progress

#269 Update smaller set of depenencies
  client/api/resource.js
  package-lock.json
  package.json
  server/script/preflight.js
Labels: :point_left: needs code review

#271 Editor issues - loader and repository not loaded
  client/api/resource.js
  client/components/editor/index.vue
Labels: :point_left: needs code review, :rotating_light: bug
