Repository ExtensionEngine/tailor, pull requests merged in 2019-10, with the labels that each got.

#354 Use @extensionengine/eslint-config
  .eslintrc.js
  client/api/request.js
  client/components/common/tce-core/QuestionContainer/Question.vue
  client/components/common/tce-core/QuestionContainer/index.vue
  client/components/content-elements/tce-drag-drop/edit/index.vue
  client/components/content-elements/tce-fill-blank/edit/index.vue
  client/components/content-elements/tce-image/edit/Cropper.vue
  client/components/content-elements/tce-matching-question/edit/index.vue
  client/components/content-elements/tce-numerical-response/edit/index.vue
  client/components/content-elements/tce-single-choice/edit/index.vue
  client/components/content-elements/tce-table/edit/index.vue
  client/components/course/Sidebar/Relationship.vue
  client/components/editor/structure/AssessmentItem.vue
  client/components/editor/structure/Exams/AssessmentGroup.vue
  client/components/editor/structure/Exams/Exam.vue
  client/components/editor/structure/Exams/GroupIntroduction.vue
  client/components/editor/structure/TesList.vue
  client/router.js
  client/store/helpers/actions.js
  client/store/helpers/resource.js
  client/store/modules/activities/getters.js
  client/utils/assessment.js
  client/utils/calculatePosition.js
  client/utils/course.js
  client/utils/numberToLetter.js
  client/utils/paramsParser.js
  client/utils/revision.js
  config/shared/activities.js
  karma.conf.js
  package-lock.json
  package.json
  sequelize.config.js
  server/course/course.controller.js
  server/index.js
  server/integrations/knewton.js
  server/shared/database/config.js
  server/shared/publishing/helpers.js
  server/shared/storage/helpers.js
  server/user/user.model.js
  stylelint.config.js
Labels: :bulb: enhancement

#356 Remove tests and clean up
  .eslintignore
  client/test/e2e/custom-assertions/elementCount.js
  client/test/e2e/nightwatch.conf.js
  client/test/e2e/runner.js
  client/test/e2e/specs/test.js
  karma.conf.js
  package.json
Labels: :point_left: needs code review

#357 Add overide rule for ./extensions/**
  .eslintrc.js
Labels: :point_left: needs code review

#358 Cleanup gitignore
  .gitignore
Labels: :bulb: enhancement

#364 Use @extensionengine/stylelint-config
  README.md
  package-lock.json
  package.json
  stylelint.config.js
Labels: :bulb: enhancement

#362 Implement more advanced Jodit plugin system
  client/components/content-elements/tce-jodit-html/edit/Editor.vue
  client/components/content-elements/tce-jodit-html/edit/Toolbar.vue
  client/components/content-elements/tce-jodit-html/edit/ToolbarBuilder.js
  client/components/content-elements/tce-jodit-html/edit/controls/tooltip/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins-adapter.js
  client/components/content-elements/tce-jodit-html/edit/plugins/autofocus/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/external-toolbar/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/font-controls/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/mdi-icons/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/source-editor/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/table-popups/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/toolbar-builder/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/toolbar-popups/index.js
  client/components/content-elements/tce-jodit-html/edit/plugins/tooltip/index.js
  package-lock.json
  poi.config.js
Labels: :bulb: enhancement

#365 Replace vue-plyr with plyrue
  client/components/content-elements/tce-video/edit/index.vue
  package-lock.json
  package.json
Labels: :bulb: enhancement, :point_left: needs code review

#144 Feature/Introduce html meta properties
  client/components/common/Meta/Html.vue
  client/components/common/Meta/index.vue
Labels: :point_left: needs code review

#234 User profile settings
  client/api/auth.js
  client/components/common/Navbar.vue
  client/components/course/Settings/UserManagement/UserList.vue
  client/components/course/Sidebar/Discussion/Comment.vue
  client/components/system-settings/UserManagement/UserDialog.vue
  client/components/system-settings/UserManagement/index.vue
  client/components/user-settings/Avatar/AvatarDialog.vue
  client/components/user-settings/Avatar/index.vue
  client/components/user-settings/Info.vue
  client/components/user-settings/Security.vue
  client/components/user-settings/index.vue
  client/main.js
  client/router.js
  client/store/modules/auth/actions.js
  client/store/modules/auth/mutations.js
  client/utils/validation.js
  package-lock.json
  package.json
  server/shared/database/migrations/20190717151916-add-user-info.js
  server/user/index.js
  server/user/user.controller.js
  server/user/user.model.js
Labels: :bulb: enhancement, :point_left: needs code review

#267 Routing reconstruction
  client/api/activity.js
  client/api/asset.js
  client/api/auth.js
  client/api/course.js
  client/store/modules/comments/actions.js
  server/activity/activity.controller.js
  server/activity/index.js
  server/comment/comment.controller.js
  server/comment/index.js
  server/course/course.controller.js
  server/course/index.js
  server/revision/index.js
  server/revision/revision.controller.js
  server/router.js
  server/shared/storage/storage.router.js
  server/teaching-element/index.js
  server/teaching-element/te.controller.js
  server/user/index.js
Labels: :mag: needs QA, :point_left: needs code review

#324 Add direct link to course settings
  client/components/catalog/Card.vue
  client/store/modules/courses/getters.js
Labels: :construction: work in progress
