Repository ExtensionEngine/tailor, pull requests merged in 2019-11, with the labels that each got.

#395 Upgrade `eslint-plugin-vue` & `eslint-plugin-vuetify`
  package-lock.json
  package.json
Labels: :rotating_light: bug

#316 Use Vuetify on Activity create
  client/components/course/Outline/Activity.vue
  client/components/course/Outline/InsertActivity/CreateActivity.vue
  client/components/course/Outline/NoActivities.vue
  client/components/course/Sidebar/index.vue
  package-lock.json
Labels: :bulb: enhancement

#397 Make sure that transaction is used when cloning
  package-lock.json
  server/activity/activity.model.js
Labels: :point_left: needs code review

#337 Tweak DateTimePicker meta styling
  client/components/common/Meta/DatePicker.vue
Labels: :bulb: enhancement
