Repository ExtensionEngine/tailor, pull requests merged in 2019-02, with the labels that each got.

#176 Updated sequelize filters
  server/activity/activity.controller.js
  server/activity/activity.model.js
  server/course/hooks.js
  server/shared/publishing/helpers.js
  server/teaching-element/te.controller.js
Labels: :construction: work in progress

#180 Fix Seed script
  server/script/dbSeed.js
Labels: :rotating_light: bug

#183 Fix file upload
  server/shared/storage/storage.controller.js
  server/shared/storage/storage.router.js
Labels: :rotating_light: bug

#37 Refactoring router
  server/app.js
  server/router.js
  server/user/index.js
Labels: :bulb: enhancement
