Repository ExtensionEngine/tailor, pull requests merged in 2020-11, with the labels that each got.

#652 Implement OpenID Connect authentication
  .env.example
  client/api/request.js
  client/components/auth/Login.vue
  client/store/modules/repository/feed.js
  client/store/plugins/vuex-persist.js
  config/server/auth.js
  package-lock.json
  package.json
  poi.config.js
  server/app.js
  server/oidc/authenticated.mustache
  server/oidc/error.mustache
  server/oidc/index.js
  server/router.js
  server/shared/auth/authenticator.js
  server/shared/auth/index.js
  server/shared/auth/oidc.js
  server/user/user.model.js
Labels: :bulb: enhancement, :mag: needs QA, :point_left: needs code review

#666 Tooltip improvements
  client/components/catalog/Card/Tags/index.vue
  client/components/catalog/Container.vue
  client/components/catalog/SelectOrder.vue
  client/components/catalog/TagFilter.vue
  client/components/repository/Outline/Activity.vue
Labels: :point_left: needs code review

#671 Order tags alphabetically by name in `TagFilter` component
  client/components/catalog/TagFilter.vue
Labels: :point_left: needs code review

#672 Add hover and selected style for searched activity items
  client/components/repository/Outline/SearchResult.vue
  client/components/repository/Outline/index.vue
Labels: :point_left: needs code review

#673 Improve search input icon hover contrast
  client/components/catalog/Card/Tags/index.vue
  client/components/catalog/Card/index.vue
  client/components/catalog/Container.vue
  client/components/catalog/SelectOrder.vue
  client/components/catalog/TagFilter.vue
Labels: :point_left: needs code review

#669 Improve image loading in `tce-image`
  client/components/content-elements/tce-image/edit/index.vue
Labels: :point_left: needs code review

#681 Use 12-hour time format with AM/PM instead of 24-hours
  client/components/repository/Revisions/EntitySidebar.vue
  client/components/repository/Revisions/RevisionItem.vue
  client/components/repository/common/Sidebar/Publishing.vue
Labels: :mag: needs QA

#677 Ensure that customResolver is returning a promise
  server/shared/content-plugins/elementRegistry.js
Labels: :point_left: needs code review, :rotating_light: bug

#683 Task: Remove hover effect from the chip
  client/assets/stylesheets/common/_all.scss
  client/assets/stylesheets/common/_chips.scss
  client/components/catalog/Card/index.vue
  client/components/common/Footer.vue
  client/components/common/SelectElement/SelectActivity.vue
  client/components/common/tce-core/AssessmentItem.vue
  client/components/content-elements/tce-drag-drop/edit/index.vue
  client/components/content-elements/tce-fill-blank/edit/index.vue
  client/components/repository/Outline/SearchResult.vue
  client/components/repository/common/LabelChip.vue
  client/components/repository/common/Sidebar/Body.vue
  client/components/system-settings/index.vue
  client/components/user-settings/index.vue
Labels: :bulb: enhancement, :mag: needs QA
