Repository ExtensionEngine/tailor, pull requests merged in 2020-10, with the labels that each got.

#581 Implement activity prepend
  client/components/editor/structure/ContentContainers/Container.vue
  client/components/repository/common/ActivityOptions/Menu.vue
  client/components/repository/common/ActivityOptions/Toolbar.vue
  client/components/repository/common/ActivityOptions/common.js
  client/components/repository/common/CopyActivity/index.vue
  client/components/repository/common/CreateDialog/index.vue
  client/store/modules/repository/activities/getters.js
  client/utils/InsertLocation.js
  client/utils/calculatePosition.js
Labels: :point_left: needs code review

#603 Rewrite `calculateInsertPosition` getter as action
  client/components/repository/common/CopyActivity/index.vue
  client/components/repository/common/CreateDialog/index.vue
  client/store/modules/repository/activities/actions.js
  client/store/modules/repository/activities/getters.js
Labels: :mag: needs QA

#590 Use plyrue instead vue-aplayer
  client/components/content-elements/tce-audio/edit/index.vue
  package-lock.json
  package.json
Labels: :construction: work in progress, :rotating_light: bug

#615 Fixed issue with element focus event subscription
  client/EventBus.js
  client/components/editor/ActivityContent/index.vue
Labels: :mag: needs QA

#591 Improve discussion notification email UI
  client/assets/img/default-email-logo.svg
  server/comment/hooks.js
  server/shared/mail/index.js
  server/shared/mail/render.js
  server/shared/mail/templates/comment.mjml
  server/shared/mail/templates/components/head.mjml
  server/shared/mail/templates/components/user-row.mjml
Labels: :point_left: needs code review

#579 Fix asset resolving
  server/shared/storage/helpers.js
Labels: :mag: needs QA, :point_left: needs code review

#606 Limit embed height
  client/components/content-elements/tce-carousel/edit/Toolbar.vue
  client/components/content-elements/tce-embed/edit/Toolbar.vue
  client/components/editor/Toolbar/index.vue
Labels: :mag: needs QA

#604 Dissalow non-integer keys on exam time input field
  client/components/content-containers/tcc-exam/edit/AssessmentGroup.vue
Labels: :mag: needs QA

#569 Implement InputAsset element URL input validation
  client/components/common/InputAsset.vue
  client/components/content-elements/tce-embed/edit/Toolbar.vue
  client/components/content-elements/tce-pdf/edit/index.vue
  client/utils/validation.js
  package-lock.json
  package.json
Labels: :construction: work in progress

#463 Refactor logging
  .env.example
  server/app.js
  server/index.js
  server/revision/hooks.js
  server/script/addAdmin.js
  server/script/addIntegration.js
  server/script/detachDeletedRepos.js
  server/script/fixRevisionUrls.js
  server/script/generateIntegrationToken.js
  server/script/inviteAdmin.js
  server/shared/database/config.js
  server/shared/database/index.js
  server/shared/logger.js
  server/shared/mail/index.js
  server/shared/origin.js
  server/shared/transfer/transfer.service.js
Labels: :bulb: enhancement

#623 Set min attribute on exam input
  client/components/content-containers/tcc-exam/edit/AssessmentGroup.vue
Labels: :mag: needs QA

#449 Updated custom container support
  README.md
  client/components/common/tce-core/AddElement/index.vue
  client/components/content-containers/tcc-assessment-pool/info.js
  client/components/content-containers/tcc-assessment-pool/util.js
  client/components/content-containers/tcc-exam/info.js
  client/components/content-containers/tcc-exam/util.js
  client/components/editor/ActivityContent/index.vue
  client/components/editor/index.vue
  client/components/editor/structure/ContentContainers/index.vue
  client/components/system-settings/ContentElements.vue
  client/content-plugins/ComponentRegistry.js
  client/content-plugins/ContainerRegistry.js
  client/content-plugins/ElementRegistry.js
  client/content-plugins/MetaRegistry.js
  client/store/modules/editor/getters.js
  config/shared/activities-rc.js
  config/shared/activities.js
  server/content-element/content-element.controller.js
  server/content-element/content-element.model.js
  server/shared/content-plugins/containerRegistry.js
  server/shared/publishing/helpers.js
Labels: :mag: needs QA, :point_left: needs code review

#566 Feature/editor sidebar activity tree updates
  client/components/editor/Sidebar/Navigation.vue
  client/components/editor/Sidebar/index.vue
Labels: :bulb: enhancement, :construction: work in progress

#636 Add required class to all inputs with required rule
  client/components/auth/ForgotPassword.vue
  client/components/auth/Login.vue
  client/components/auth/ResetPassword.vue
  client/components/catalog/Add.vue
  client/components/catalog/Card/Tags/AddTag.vue
  client/components/content-elements/tce-carousel/edit/Toolbar.vue
  client/components/content-elements/tce-embed/edit/Toolbar.vue
  client/components/meta-inputs/meta-input/Edit.vue
  client/components/meta-inputs/meta-textarea/Edit.vue
  client/components/repository/Settings/CloneModal.vue
  client/components/repository/Settings/UserManagement/AddUserDialog.vue
  client/components/repository/common/Sidebar/Relationship.vue
  client/components/system-settings/UserManagement/UserDialog.vue
  client/components/user-settings/ChangePasswordDialog.vue
  client/components/user-settings/Info.vue
Labels: :mag: needs QA

#642 Update tailor config example
  README.md
  tailor.config.js.example
Labels: :point_left: needs code review

#641 Implement input asset empty save and cancel button feature
  client/components/common/InputAsset.vue
  client/components/content-elements/tce-pdf/edit/Toolbar.vue
  client/components/content-elements/tce-video/edit/Toolbar.vue
  server/shared/storage/helpers.js
Labels: :mag: needs QA

#647 Restored the deprecated tes prop for containers
  client/components/editor/structure/ContentContainers/index.vue
  client/content-plugins/ContainerRegistry.js
  client/content-plugins/validation/ValidationService.js
  client/content-plugins/validation/index.js
  client/content-plugins/validation/types.js
Labels: :mag: needs QA, :point_left: needs code review

#644 Update content element deletedAt field manually on patch
  server/content-element/content-element.controller.js
Labels: :mag: needs QA

#650 Fix assessment items expanding/collapsing
  client/components/content-containers/tcc-assessment-pool/edit/index.vue
Labels: :point_left: needs code review
