Repository ExtensionEngine/tailor, pull requests merged in 2020-12, with the labels that each got.

#667 Comment improvements
  client/components/repository/common/Sidebar/Discussion/Comment.vue
  client/components/repository/common/Sidebar/Discussion/TextEditor.vue
  server/comment/hooks.js
  server/shared/mail/index.js
  server/shared/mail/templates/comment.mjml
Labels: :construction: work in progress

#663 Fix duplicated comments
  server/shared/mail/render.js
  server/shared/mail/templates/comment.mjml
  server/shared/mail/templates/components/user-row.mjml
Labels: :grey_question: question

#692 Update editor toolbar positioning in DOM and hide element toolbar when element is being dragged
  client/components/common/tce-core/ElementList.vue
  client/components/common/tce-core/ElementToolbar.vue
  client/components/editor/ActivityContent/index.vue
  client/components/editor/Sidebar/index.vue
  client/components/editor/Toolbar/index.vue
  client/components/editor/index.vue
Labels: :mag: needs QA

#645 Content element comments
  client/components/common/mixins/commentEventListeners.js
  client/components/common/tce-core/ContainedContent.vue
  client/components/common/tce-core/ContentElement.vue
  client/components/common/tce-core/Discussion/Comment.vue
  client/components/common/tce-core/Discussion/TextEditor.vue
  client/components/common/tce-core/Discussion/Thread.vue
  client/components/common/tce-core/Discussion/index.vue
  client/components/common/tce-core/ElementDiscussion.vue
  client/components/common/tce-core/ElementList.vue
  client/components/common/tce-core/Events/DiscussionEvent.js
  client/components/common/tce-core/index.js
  client/components/content-containers/tcc-default/edit/index.vue
  client/components/editor/ActivityContent/ContainerList.vue
  client/components/editor/ActivityContent/index.vue
  client/components/editor/Sidebar/Discussion.vue
  client/components/editor/Sidebar/index.vue
  client/components/editor/index.vue
  client/components/repository/Revisions/EntityRevisions.vue
  client/components/repository/Revisions/RevisionItem.vue
  client/components/repository/common/ActivityDiscussion.vue
  client/components/repository/common/Sidebar/Body.vue
  client/components/repository/common/Sidebar/Discussion/index.vue
  client/store/modules/repository/comments/actions.js
  client/store/modules/repository/comments/getters.js
  client/store/modules/repository/comments/index.js
  client/store/modules/repository/comments/mutations.js
  client/store/plugins/vuex-persist.js
  server/comment/comment.controller.js
  server/comment/comment.model.js
  server/comment/hooks.js
  server/shared/database/migrations/20201113162457-add-element-id-to-comment.js
  server/shared/mail/index.js
Labels: :construction: work in progress

#689 Move JWT to cookie
  .env.example
  client/api/auth.js
  client/api/request.js
  client/components/common/Navbar.vue
  client/components/user-settings/ChangePasswordDialog.vue
  client/main.js
  client/router.js
  client/store/index.js
  client/store/modules/auth/actions.js
  client/store/modules/auth/index.js
  client/store/modules/auth/mutations.js
  client/store/modules/repository/actions.js
  client/store/modules/repository/feed.js
  client/store/plugins/vuex-persist.js
  client/utils/auth.js
  config/server/auth.js
  package-lock.json
  package.json
  poi.config.js
  server/app.js
  server/oidc/authenticated.mustache
  server/oidc/index.js
  server/shared/auth/authenticator.js
  server/shared/auth/index.js
  server/user/index.js
  server/user/user.controller.js
Labels: :mag: needs QA

#697 Allow signup over OIDC
  .env.example
  config/server/auth.js
  server/shared/auth/index.js
Labels: :mag: needs QA

#695 Serve storage assets through CloudFront
  .env.example
  config/server/storage.js
  package-lock.json
  package.json
  poi.config.js
  server/app.js
  server/repository/index.js
  server/shared/storage/helpers.js
  server/shared/storage/proxy/index.js
  server/shared/storage/proxy/mw.js
  server/shared/storage/proxy/providers/cloudfront.js
  server/shared/storage/proxy/providers/local.js
  server/shared/storage/storage.controller.js
  server/shared/storage/util.js
  server/shared/storage/validation.js
Labels: :mag: needs QA

#679 Feature: Improve image loading speed
  client/components/content-elements/tce-image/edit/index.vue
Labels: :bulb: enhancement, :point_left: needs code review

#703 Custom TCE hooks
  client/components/content-elements/tce-image/index.js
  client/components/content-elements/tce-image/info.js
  client/components/content-elements/tce-image/util.js
  config/server/storage.js
  server/content-element/content-element.model.js
  server/content-element/hooks.js
  server/shared/content-plugins/elementHooks.js
  server/shared/content-plugins/elementRegistry.js
  server/shared/storage/helpers.js
  server/shared/storage/storage.controller.js
Labels: :mag: needs QA, :point_left: needs code review

#705 Fix handleStatics deprecation message
  server/shared/content-plugins/elementRegistry.js
Labels: :point_left: needs code review

#708 Change user email to @example in seed script and in .env.example sender address
  .env.example
  server/shared/database/seeds/20181115140901-insert-users.js
Labels: :point_left: needs code review
