Repository ExtensionEngine/tailor, pull requests merged in 2020-07, with the labels that each got.

#550 Remove the apostrophe from matching question component
  client/components/content-elements/tce-matching-question/edit/index.vue
Labels: :mag: needs QA, :point_left: needs code review

#551 Set v-carousel height explicitly
  client/components/content-elements/tce-carousel/edit/index.vue
Labels: :mag: needs QA

#553 Sort carousel item indices numerically
  client/components/content-elements/tce-carousel/edit/index.vue
Labels: :mag: needs QA, :point_left: needs code review

#545 Metadata input extensions
  .gitignore
  client/components/common/Meta/index.vue
  client/components/common/tce-core/MetaInput.vue
  client/components/common/tce-core/utils.js
  client/components/editor/Sidebar/ElementSidebar/ElementMeta/Inputs.vue
  client/components/meta-inputs/meta-checkbox/Edit.vue
  client/components/meta-inputs/meta-checkbox/index.js
  client/components/meta-inputs/meta-color/Edit/ColorInput.vue
  client/components/meta-inputs/meta-color/Edit/index.vue
  client/components/meta-inputs/meta-color/index.js
  client/components/meta-inputs/meta-datetime/Edit/DatePicker.vue
  client/components/meta-inputs/meta-datetime/Edit/TimePicker.vue
  client/components/meta-inputs/meta-datetime/Edit/index.vue
  client/components/meta-inputs/meta-datetime/index.js
  client/components/meta-inputs/meta-file/Edit.vue
  client/components/meta-inputs/meta-file/index.js
  client/components/meta-inputs/meta-html/Edit.vue
  client/components/meta-inputs/meta-html/index.js
  client/components/meta-inputs/meta-input/Edit.vue
  client/components/meta-inputs/meta-input/index.js
  client/components/meta-inputs/meta-select/Edit.vue
  client/components/meta-inputs/meta-select/index.js
  client/components/meta-inputs/meta-switch/Edit.vue
  client/components/meta-inputs/meta-switch/index.js
  client/components/meta-inputs/meta-textarea/Edit.vue
  client/components/meta-inputs/meta-textarea/index.js
  client/components/repository/Settings/General.vue
  client/components/repository/common/CreateDialog/index.vue
  client/components/repository/common/Sidebar/Body.vue
  client/content-plugins/ComponentRegistry.js
  client/content-plugins/ContainerRegistry.js
  client/content-plugins/ElementRegistry.js
  client/content-plugins/MetaRegistry.js
  client/content-plugins/index.js
  config/shared/core-meta.js
  extensions/meta-inputs/.gitkeep
Labels: :bulb: enhancement

#556 Upgrade sequelize from v5 to v6
  package-lock.json
  package.json
  server/index.js
  server/shared/database/config.js
  server/shared/database/helpers.js
  server/shared/database/index.js
  server/shared/database/migrations/20181115140903-course-user-relationship.js
  server/shared/database/migrations/20200130124252-create-repository-tag.js
Labels: :mag: needs QA

#560 Fixed issue with browser back button not working:
  client/components/repository/common/selectActivity.js
  client/components/repository/index.vue
Labels: :point_left: needs code review, :rotating_light: bug

#565 Fixed activity selection in outline:
  client/components/repository/index.vue
Labels: :mag: needs QA, :point_left: needs code review, :rotating_light: bug

#570 Fix unused transaction in Activity.remove method
  server/activity/activity.model.js
Labels: :mag: needs QA, :point_left: needs code review, :rotating_light: bug
