Repository ExtensionEngine/tailor, pull requests merged in 2020-08, with the labels that each got.

#564 Fix activities reorder on latest schema config
  config/shared/activities.js
  server/activity/activity.model.js
Labels: :point_left: needs code review, :rotating_light: bug

#576 Add reinvite button in user edit dialog
  client/components/system-settings/UserManagement/UserDialog.vue
Labels: :mag: needs QA, :point_left: needs code review

#537 Remove word component from ElementPlaceholder
  client/components/common/tce-core/ElementPlaceholder.vue
  client/components/content-elements/tce-accordion/edit/index.vue
  client/components/content-elements/tce-audio/edit/index.vue
  client/components/content-elements/tce-brightcove-video/edit/index.vue
  client/components/content-elements/tce-carousel/edit/index.vue
  client/components/content-elements/tce-embed/edit/index.vue
  client/components/content-elements/tce-html/edit/index.vue
  client/components/content-elements/tce-image/edit/index.vue
  client/components/content-elements/tce-pdf/edit/index.vue
  client/components/content-elements/tce-video/edit/index.vue
Labels: :bulb: enhancement, :mag: needs QA, :point_left: needs code review

#536 Introduce add element options on element list and container
  client/components/common/tce-core/ElementList.vue
  client/components/common/tce-core/EmbeddedContainer.vue
Labels: :bulb: enhancement, :point_left: needs code review

#583 Send activity link with discussion notification
  server/comment/hooks.js
  server/shared/mail/index.js
  server/shared/mail/templates/comment.mjml
  server/shared/mail/templates/comment.txt
Labels: :point_left: needs code review
