Repository ExtensionEngine/tailor, pull requests merged in 2020-05, with the labels that each got.

#487 user comments notification
  client/components/editor/Sidebar/Discussion.vue
  client/components/editor/Sidebar/index.vue
  client/store/modules/repository/comments/getters.js
  client/store/modules/repository/comments/index.js
  client/store/modules/repository/comments/mutations.js
  client/store/plugins/vuex-persist.js
Labels: :point_left: needs code review

#500 Element toolbar bugfix
  client/components/common/tce-core/ElementToolbar.vue
Labels: :mag: needs QA

#447 Placed activity assessments inside of a container
  README.md
  client/components/common/ContentPreview/Element.vue
  client/components/common/tce-core/AddElement/index.vue
  client/components/common/tce-core/AssessmentItem.vue
  client/components/common/tce-core/ElementToolbar.vue
  client/components/common/tce-core/QuestionContainer/index.vue
  client/components/content-containers/tcc-assessment-pool/edit/index.vue
  client/components/content-containers/tcc-assessment-pool/index.js
  client/components/content-containers/tcc-assessment-pool/info.js
  client/components/content-containers/tcc-assessment-pool/util.js
  client/components/content-containers/tcc-exam/edit/Assessment.vue
  client/components/content-containers/tcc-exam/edit/AssessmentGroup.vue
  client/components/content-containers/tcc-exam/edit/GroupIntroduction.vue
  client/components/content-containers/tcc-exam/edit/index.vue
  client/components/editor/ActivityContent/index.vue
  client/components/editor/ContentElement.vue
  client/components/editor/Sidebar/ElementSidebar/ElementMeta/Relationships/index.vue
  client/components/editor/structure/ContentContainers/Container.vue
  client/components/editor/structure/ContentContainers/index.vue
  client/components/editor/structure/ElementList.vue
  client/components/repository/Revisions/EntityRevisions.vue
  client/router.js
  client/store/helpers/actions.js
  client/store/index.js
  client/store/modules/editor/getters.js
  client/store/modules/repository/actions.js
  client/store/modules/repository/content-elements/actions.js
  client/store/modules/repository/content-elements/getters.js
  client/store/modules/repository/content-elements/index.js
  client/store/modules/repository/content-elements/mutations.js
  client/store/modules/repository/getters.js
  client/store/modules/repository/index.js
  client/store/modules/repository/tes/getters.js
  client/utils/revision.js
  config/shared/activities-rc.js
  config/shared/core-containers.js
  package-lock.json
  package.json
  server/content-element/content-element.controller.js
  server/script/migrateAssessmentPools.js
  server/shared/publishing/helpers.js
Labels: :mag: needs QA

#509 Fixed issues with repository graph
  client/components/repository/TreeView/TreeGraph.vue
  client/components/repository/TreeView/index.vue
Labels: :mag: needs QA

#485 Vuetify assessments
  client/components/common/tce-core/AssessmentItem.vue
  client/components/common/tce-core/ContainedContent.vue
  client/components/common/tce-core/ContentElement.vue
  client/components/common/tce-core/ElementPlaceholder.vue
  client/components/common/tce-core/QuestionContainer/Controls.vue
  client/components/common/tce-core/QuestionContainer/Feedback.vue
  client/components/common/tce-core/QuestionContainer/Feedback/FeedbackItem.vue
  client/components/common/tce-core/QuestionContainer/Feedback/index.vue
  client/components/common/tce-core/QuestionContainer/Question.vue
  client/components/common/tce-core/QuestionContainer/index.vue
  client/components/content-containers/tcc-exam/edit/Assessment.vue
  client/components/content-elements/tce-drag-drop/edit/index.vue
  client/components/content-elements/tce-embed/edit/index.vue
  client/components/content-elements/tce-fill-blank/edit/index.vue
  client/components/content-elements/tce-html/edit/index.vue
  client/components/content-elements/tce-image/edit/index.vue
  client/components/content-elements/tce-matching-question/edit/index.vue
  client/components/content-elements/tce-multiple-choice/edit/index.vue
  client/components/content-elements/tce-numerical-response/edit/index.vue
  client/components/content-elements/tce-single-choice/edit/index.vue
  client/components/content-elements/tce-text-response/edit/index.vue
  client/components/content-elements/tce-true-false/edit/index.vue
  client/components/editor/ActivityContent/index.vue
  client/utils/assessment.js
  package-lock.json
  package.json
Labels: :mag: needs QA

#527 Make logo and title a tag
  client/components/common/Navbar.vue
Labels: :bulb: enhancement, :point_left: needs code review

#525 fix repository list with tag filter applied
  client/store/modules/repositories/mutations.js
Labels: :mag: needs QA, :point_left: needs code review
