Repository ExtensionEngine/tailor, pull requests merged in 2020-03, with the labels that each got.

#429 Feature/repository tags
  client/api/repository.js
  client/api/tag.js
  client/components/catalog/Card/Tags/AddTag.vue
  client/components/catalog/Card/Tags/index.vue
  client/components/catalog/Card/index.vue
  client/components/catalog/Container.vue
  client/components/catalog/TagFilter.vue
  client/components/catalog/TagFilterSelection.vue
  client/store/modules/repositories/actions.js
  client/store/modules/repositories/getters.js
  client/store/modules/repositories/index.js
  client/store/modules/repositories/mutations.js
  server/repository/index.js
  server/repository/repository.controller.js
  server/repository/repository.model.js
  server/router.js
  server/shared/database/index.js
  server/shared/database/migrations/20200130124211-create-tag.js
  server/shared/database/migrations/20200130124252-create-repository-tag.js
  server/tag/index.js
  server/tag/repositoryTag.model.js
  server/tag/tag.controller.js
  server/tag/tag.model.js
Labels: :construction: work in progress

#461 Add `nodemon` config
  nodemon.json
  package.json
Labels: :bulb: enhancement

#460 Update `@extensionengine/eslint-config`
  build/plugins/brand.js
  client/components/content-containers/tcc-exam/util.js
  config/shared/activities.js
  package-lock.json
  package.json
  server/app.js
  server/comment/hooks.js
  server/comment/index.js
  server/index.js
  server/repository/index.js
  server/repository/repository.controller.js
  server/script/detachDeletedRepos.js
  server/script/fixRevisionUrls.js
  server/script/sequelize.js
  server/shared/auth/mw.js
  server/shared/database/index.js
  server/shared/database/seeds/20181115140901-insert-users.js
  server/shared/publishing/publishing.service.js
  server/shared/storage/providers/filesystem.js
  server/tag/tag.controller.js
Labels: :bulb: enhancement, :mag: needs QA

#464 add search on tag filter drop down menu
  client/api/tag.js
  client/components/catalog/Card/Tags/AddTag.vue
  client/components/catalog/Container.vue
  client/components/catalog/TagFilter.vue
  client/store/modules/repositories/actions.js
  server/tag/tag.controller.js
  server/tag/tag.model.js
Labels: :mag: needs QA, :point_left: needs code review
