Repository ExtensionEngine/tailor, pull requests merged in 2021-04, with the labels that each got.

#796 Apply element fetch hooks on revisions fetch
  server/content-element/content-element.model.js
  server/content-element/hooks.js
  server/revision/revision.model.js
Labels: :mag: needs QA, :point_left: needs code review

#803 Implement user name format validation
  client/components/system-settings/UserManagement/UserDialog.vue
  client/components/user-settings/Info.vue
  client/utils/validation.js
Labels: :mag: needs QA, :point_left: needs code review

#793 Trigger webhook on repository details publish
  server/shared/publishing/helpers.js
  server/shared/publishing/publishing.service.js
Labels: :mag: needs QA, :point_left: needs code review

#814 Add avatar to workflow assignee dropdown
  client/components/repository/Workflow/Sidebar/FieldGroup.vue
Labels: :mag: needs QA, :point_left: needs code review

#811 Add common workflow status selection
  client/components/repository/Workflow/Filters/index.vue
  client/components/repository/Workflow/SelectStatus.vue
  client/components/repository/Workflow/Sidebar/FieldGroup.vue
Labels: :mag: needs QA

#788 Add schema filter to catalog:
  client/components/catalog/Container.vue
  client/components/catalog/RepositoryFilter.vue
  client/components/catalog/RepositoryFilterSelection/SelectedFilter.vue
  client/components/catalog/RepositoryFilterSelection/index.vue
  client/components/catalog/TagFilterSelection.vue
  client/components/catalog/repositoryFilterConfigs.js
  client/store/modules/repositories/getters.js
  client/store/modules/repositories/index.js
  client/store/modules/repositories/mutations.js
  server/repository/repository.controller.js
Labels: :bulb: enhancement, :ok_hand: passed QA

#812 Fixed login route redirect for already logged users
  client/router.js
Labels: :point_left: needs code review

#816 User management & profile improvements
  client/components/repository/Settings/Sidebar.vue
  client/components/user-settings/Info.vue
  client/utils/validation.js
Labels: :mag: needs QA, :point_left: needs code review

#819 Unexpected element width expand fix
  package-lock.json
  package.json
Labels: :mag: needs QA

#822 Hide element toolbar on activity/editor change
  client/components/editor/index.vue
Labels: :ok_hand: passed QA, :point_left: needs code review

#825 Improve tracker for active users
  .env.example
  client/components/common/mixins/userTracking.js
  client/store/modules/repository/actions.js
  config/server/store.js
  package-lock.json
  package.json
  server/repository/feed/store.js
  server/shared/store/index.js
  server/shared/store/providers/local.js
  server/shared/store/providers/redis.js
Labels: :mag: needs QA, :point_left: needs code review

#815 Integrate reset token validation on reset password landing
  client/api/auth.js
  client/components/auth/ForgotPassword.vue
  client/components/auth/ResetPassword.vue
  client/store/modules/auth/actions.js
  package-lock.json
  package.json
  server/shared/auth/index.js
  server/shared/request/mw.js
  server/user/index.js
Labels: :point_left: needs code review

#817 Add existing repository name warning message
  client/components/catalog/Add.vue
  client/components/meta-inputs/meta-textarea/Edit.vue
  client/components/repository/Settings/General.vue
  client/components/repository/Settings/index.vue
  client/components/repository/common/RepositoryNameField.vue
  client/components/repository/index.vue
  server/repository/repository.controller.js
Labels: :point_left: needs code review
