Repository ExtensionEngine/tailor, pull requests merged in 2021-03, with the labels that each got.

#758 Fixed issue with publishing diff date chip text color
  client/components/editor/Toolbar/index.vue
Labels: :rotating_light: bug

#767 Fix publish diff for deleted container
  client/components/editor/ActivityContent/PublishDiffProvider.vue
  package.json
  server/activity/activity.model.js
  server/content-element/hooks.js
Labels: :mag: needs QA, :point_left: needs code review

#773 Prevent creation of mutiple elements by clicking
  client/components/repository/common/CreateDialog/index.vue
Labels: :construction: work in progress

#756 Fix: Image not visible on all slides inside the carousel element
  client/components/content-elements/tce-image/edit/index.vue
Labels: :mag: needs QA, :rotating_light: bug

#779 Remove debounce function from the store.subscribe
  client/components/editor/ActivityContent/index.vue
Labels: :point_left: needs code review, :rotating_light: bug

#785 Fix unused transaction in update repository roles migration
  server/shared/database/migrations/20191023083031-update-repository-roles.js
Labels: :point_left: needs code review

#766 Fix comment input ref
  client/components/common/tce-core/ContentElement.vue
  client/components/common/tce-core/Discussion/index.vue
  client/components/common/tce-core/ElementDiscussion.vue
  client/components/repository/common/ActivityDiscussion.vue
Labels: :point_left: needs code review

#784 Fix: Add due date warning to outline's sidebar
  client/components/repository/Workflow/Overview/DueDate.vue
  client/components/repository/common/Sidebar/Status/index.vue
  client/components/repository/common/WorkflowDueDate.vue
  client/utils/date.js
Labels: :ok_hand: passed QA, :point_left: needs code review

#787 Add status filter to Progress page
  client/App.vue
  client/components/repository/Workflow/Filters/Assignee.vue
  client/components/repository/Workflow/Filters/Status.vue
  client/components/repository/Workflow/Filters/index.vue
  client/components/repository/Workflow/index.vue
  client/components/repository/common/AssigneeAvatar.vue
Labels: :ok_hand: passed QA, :point_left: needs code review

#789 Replace active users map with in-memory key-value store
  .env.example
  config/server/index.js
  config/server/store.js
  package-lock.json
  package.json
  server/repository/feed/controller.js
  server/repository/feed/store.js
  server/shared/store/index.js
  server/shared/store/providers/local.js
  server/shared/store/providers/redis.js
Labels: :bulb: enhancement, :mag: needs QA

#798 Improve assets migration script
  server/script/migrateAssetsLocation.js
Labels: :bulb: enhancement, :point_left: needs code review

#800 Fix broken activity delete action, hide discussion on empty progress page
  client/components/repository/Workflow/Sidebar/index.vue
  client/store/helpers/mutations.js
  client/store/modules/repository/activities/actions.js
  client/store/modules/repository/getters.js
  common/sse.js
  server/activity/activity.model.js
  server/activity/hooks.js
Labels: :mag: needs QA

#757 Feature: Add assets permissions
  client/api/asset.js
  client/components/common/mixins/upload.js
  client/components/content-elements/tce-image/server/index.js
  config/server/storage.js
  package.json
  server/app.js
  server/repository/index.js
  server/repository/proxy.js
  server/repository/storage.js
  server/router.js
  server/script/detachDeletedRepos.js
  server/script/migrateAssetsLocation.js
  server/shared/auth/authenticator.js
  server/shared/content-plugins/elementRegistry.js
  server/shared/publishing/helpers.js
  server/shared/storage/helpers.js
  server/shared/storage/index.js
  server/shared/storage/proxy/index.js
  server/shared/storage/proxy/mw.js
  server/shared/storage/proxy/providers/cloudfront.js
  server/shared/storage/proxy/providers/local.js
  server/shared/storage/storage.controller.js
  server/shared/storage/storage.router.js
  server/shared/transfer/default/index.js
Labels: :bulb: enhancement, :point_left: needs code review

#791 Handle missing schema meta validators
  client/utils/validation.js
Labels: :mag: needs QA, :point_left: needs code review
