Repository ExtensionEngine/tailor, pull requests merged in 2021-01, with the labels that each got.

#710 Avoid compiling server files inside the custom content element
  .eslintrc.js
  client/components/content-elements/tce-image/server/index.js
  client/components/content-elements/tce-scorm/server/index.js
  client/content-plugins/ComponentRegistry.js
  server/shared/content-plugins/BaseRegistry.js
Labels: :point_left: needs code review, :rotating_light: bug

#702 Implement publish notification system
  .env.example
  config/server/consumer.js
  config/server/index.js
  package-lock.json
  package.json
  server/script/inviteAdmin.js
  server/shared/publishing/publishing.service.js
  server/shared/util/Deferred.js
  server/shared/webhookProvider.js
Labels: :point_left: needs code review

#659 Ability to view last published state
  client/api/revision.js
  client/assets/stylesheets/common/_variables.scss
  client/components/common/tce-core/AddElement/InlineActivator.vue
  client/components/common/tce-core/AssessmentItem.vue
  client/components/common/tce-core/ContainedContent.vue
  client/components/common/tce-core/ContentElement.vue
  client/components/common/tce-core/ElementList.vue
  client/components/common/tce-core/PublishDiffChip.vue
  client/components/content-containers/tcc-assessment-pool/edit/index.vue
  client/components/content-containers/tcc-default/edit/index.vue
  client/components/editor/ActivityContent/ContainerList.vue
  client/components/editor/ActivityContent/PublishDiffProvider.vue
  client/components/editor/ActivityContent/index.vue
  client/components/editor/Toolbar/ActivityActions.vue
  client/components/editor/Toolbar/index.vue
  client/components/editor/index.vue
  client/store/modules/editor/index.js
  client/store/modules/editor/mutations.js
  server/activity/activity.model.js
  server/revision/index.js
  server/revision/revision.controller.js
  server/revision/revision.model.js
  server/revision/revision.service.js
Labels: :point_left: needs code review

#716 Feature: Enable adding environment variables for TCE server hooks
  client/components/editor/ActivityContent/ContainerList.vue
  config/server/index.js
  config/server/tce.js
  server/content-element/hooks.js
Labels: :bulb: enhancement, :point_left: needs code review

#722 Initialize webhook provider only if configured
  server/shared/publishing/publishing.service.js
  server/shared/webhookProvider.js
Labels: :point_left: needs code review
