Repository ExtensionEngine/tailor, pull requests merged in 2021-05, with the labels that each got.

#846 Update graph view icon color to secondary color
  client/components/repository/Outline/Toolbar.vue
  package-lock.json
  package.json
Labels: :ok_hand: passed QA, :point_left: needs code review

#837 Don't send an email after self-assign to the activity
  server/activity/activity.controller.js
  server/activity/status.hooks.js
Labels: :ok_hand: passed QA, :point_left: needs code review

#850 Scroll to the opened activity if it is not visible
  client/components/editor/Sidebar/Navigation.vue
Labels: :ok_hand: passed QA, :point_left: needs code review

#848 Change open in new tab icon color from pink to white
  client/components/common/ContentPreview/Element.vue
Labels: :ok_hand: passed QA, :point_left: needs code review

#849 Fix reset password feature not working
  client/components/auth/ResetPassword.vue
Labels: :mag: needs QA, :point_left: needs code review, :rotating_light: bug

#831 Fix: Relationships grouped by name
  client/components/repository/common/LabelChip.vue
  client/components/repository/common/Sidebar/Relationship.vue
Labels: :ok_hand: passed QA, :point_left: needs code review

#829 Fix tce-carousel slide focus when adding a new slide
  client/components/content-elements/tce-carousel/edit/index.vue
Labels: :mag: needs QA, :point_left: needs code review

#847 Limit the comment input to 600 chars
  client/components/common/tce-core/Discussion/index.vue
Labels: :mag: needs QA, :point_left: needs code review, :raising_hand_man: feature request

#852 Storage proxy's signed cookies set to the wrong domain
  package-lock.json
  package.json
  server/shared/storage/proxy/index.js
  server/shared/storage/proxy/mw.js
  server/shared/storage/proxy/providers/local.js
Labels: :point_left: needs code review

#851 Change avatar border color on active state
  client/App.vue
  client/assets/stylesheets/common/_variables.scss
  client/components/repository/Outline/Toolbar.vue
  client/components/repository/Workflow/Filters/Assignee.vue
Labels: :mag: needs QA, :point_left: needs code review

#836 Implement max login attempts
  client/components/auth/Login.vue
  server/shared/request/mw.js
  server/user/index.js
  server/user/mw.js
Labels: :bulb: enhancement, :mag: needs QA

#854 Edit button text on the reset password page
  client/components/auth/ResetPassword.vue
Labels: :ok_hand: passed QA, :point_left: needs code review

#739 Vuetify 2.5
  client/components/catalog/Add.vue
  package-lock.json
  package.json
Labels: :construction: work in progress

#801 Update tce-jodit
  package-lock.json
  package.json
Labels: :ok_hand: passed QA, :point_left: needs code review

#868 Update monorepo packages
  lerna.json
  package-lock.json
  package.json
  packages/core-components/package-lock.json
  packages/core-components/package.json
Labels: :point_left: needs code review
