Repository ExtensionEngine/tailor, pull requests merged in 2021-02, with the labels that each got.

#706 CE Comments resolvement
  client/components/common/ConfirmationModal.vue
  client/components/common/mixins/commentEventListeners.js
  client/components/common/tce-core/Discussion/ResolveButton.vue
  client/components/common/tce-core/Discussion/TextEditor.vue
  client/components/common/tce-core/Discussion/Thread/Comment/Header.vue
  client/components/common/tce-core/Discussion/Thread/Comment/Preview.vue
  client/components/common/tce-core/Discussion/Thread/Comment/index.vue
  client/components/common/tce-core/Discussion/Thread/index.vue
  client/components/common/tce-core/Discussion/index.vue
  client/components/common/tce-core/ElementDiscussion.vue
  client/components/common/tce-core/Events/DiscussionEvent.js
  client/components/editor/ActivityContent/index.vue
  client/components/repository/common/ActivityDiscussion.vue
  client/store/modules/repository/comments/actions.js
  client/store/modules/repository/comments/getters.js
  server/comment/comment.controller.js
  server/comment/comment.model.js
  server/comment/hooks.js
  server/comment/index.js
  server/content-element/hooks.js
  server/shared/database/migrations/20210125094759-add-edited_at_column_to_comment.js
  server/shared/database/migrations/20210125094819-add-resolved_at-column-to-comment.js
Labels: :construction: work in progress

#624 Element copying feature
  client/api/repository.js
  client/components/common/ContentPreview/Element.vue
  client/components/common/ContentPreview/index.vue
  client/components/common/SelectElement/SelectActivity.vue
  client/components/common/SelectElement/SelectRepository.vue
  client/components/common/SelectElement/index.vue
  client/components/common/mixins/deprecation.js
  client/components/common/tce-core/AddElement/AddNewElement.vue
  client/components/common/tce-core/AddElement/index.vue
  client/components/common/tce-core/ElementList.vue
  client/components/common/tce-core/EmbeddedContainer.vue
  client/components/common/tce-core/QuestionContainer/Question.vue
  client/components/common/tce-core/utils.js
  client/components/content-containers/tcc-assessment-pool/edit/index.vue
  client/components/content-containers/tcc-default/edit/index.vue
  client/components/content-containers/tcc-exam/edit/AssessmentGroup.vue
  client/components/content-containers/tcc-exam/edit/GroupIntroduction.vue
  client/components/content-containers/tcc-exam/edit/index.vue
  client/components/content-elements/tce-modal/edit/Preview.vue
  client/components/content-elements/tce-modal/edit/index.vue
  client/components/editor/ActivityContent/ContainerList.vue
  client/components/editor/Sidebar/ElementSidebar/ElementMeta/Relationships/Item.vue
  client/components/repository/Outline/reorderMixin.js
  client/components/repository/common/CopyActivity/index.vue
  client/store/modules/repository/activities/actions.js
  client/store/modules/repository/content-elements/actions.js
  client/utils/calculatePosition.js
  package-lock.json
  package.json
  server/repository/index.js
  server/repository/repository.controller.js
Labels: :point_left: needs code review

#730 Move tree view to structure view
  client/components/repository/Outline/Toolbar.vue
  client/components/repository/Outline/TreeView/TreeGraph.vue
  client/components/repository/Outline/TreeView/index.vue
  client/components/repository/Outline/index.vue
  client/components/repository/Settings/Sidebar.vue
  client/components/repository/common/ActivityOptions/Menu.vue
  client/components/repository/index.vue
  client/router.js
Labels: :point_left: needs code review

#737 Fix element layout shift on selection
  client/assets/stylesheets/common/_variables.scss
  client/components/common/tce-core/ContentElement.vue
Labels: :mag: needs QA, :point_left: needs code review, :rotating_light: bug

#736 Improve silent auth
  server/oidc/index.js
Labels: :point_left: needs code review

#733 Ensure selected activity parents are always expanded
  client/components/repository/Outline/index.vue
  client/components/repository/index.vue
  client/store/modules/repository/mutations.js
Labels: :point_left: needs code review

#721 Truncate long schema names
  client/components/catalog/Card/index.vue
Labels: :point_left: needs code review

#744 Fix element revision preview
  client/components/common/tce-core/ContentElement.vue
Labels: :mag: needs QA, :point_left: needs code review

#728 Comments improvement
  client/components/common/tce-core/ContentElement.vue
  client/components/common/tce-core/ElementDiscussion.vue
  server/comment/hooks.js
  server/content-element/hooks.js
  server/shared/database/migrations/20210204115515-hydrate-edited_at-column.js
Labels: :point_left: needs code review

#745 Improve Resource helper
  client/store/helpers/resource.js
Labels: :mag: needs QA, :point_left: needs code review

#714 Fixed issue with deleted containers and publish:
  server/shared/publishing/helpers.js
  server/shared/storage/index.js
  server/shared/storage/providers/amazon.js
  server/shared/storage/providers/filesystem.js
Labels: :point_left: needs code review, :rotating_light: bug

#729 Update tce-scorm server source path
  client/components/content-elements/tce-scorm/server/index.js
  package-lock.json
  package.json
Labels: :no_entry: do not merge

#750 Update workflow config example
  tailor.config.js.example
Labels: :point_left: needs code review

#747 Fix activity repository_id foreign key error on repository import
  server/activity/activity.model.js
Labels: :point_left: needs code review

#749 Pass context to the element hooks
  server/content-element/hooks.js
  server/shared/content-plugins/elementRegistry.js
Labels: :point_left: needs code review

#748 Resolve statics for publish diff revisions
  server/revision/index.js
  server/revision/revision.controller.js
  server/revision/revision.model.js
  server/revision/revision.service.js
Labels: :point_left: needs code review

#751 Discussion text editor focus fix
  client/components/common/tce-core/Discussion/index.vue
  client/components/common/tce-core/ElementDiscussion.vue
  client/components/repository/common/ActivityDiscussion.vue
Labels: :point_left: needs code review
