Repository ExtensionEngine/tailor, pull requests merged in 2021-06, with the labels that each got.

#876 Adjust z-index on tce-audio
  client/components/content-elements/tce-audio/edit/index.vue
Labels: :mag: needs QA

#882 Improve outline performance
  client/components/repository/Outline/Activity.vue
Labels: :mag: needs QA

#895 Return if there are no filepaths
  server/shared/storage/providers/amazon.js
Labels: :rotating_light: bug

#877 Fix header to the top of the table in Progress page
  client/components/repository/Workflow/Overview/index.vue
Labels: :ok_hand: passed QA
