Repository ExtensionEngine/tailor, pull requests merged in 2022-07, with the labels that each got.

#898 Remove bootstrap 🎉
  client/assets/stylesheets/common/_vuetify.scss
  client/assets/stylesheets/main.scss
  client/assets/stylesheets/vendor/_bootstrap.scss
  client/components/catalog/Container.vue
  client/components/common/Navbar.vue
  client/components/content-containers/tcc-assessment-pool/edit/index.vue
  client/components/content-containers/tcc-exam/edit/AssessmentGroup.vue
  client/components/content-containers/tcc-exam/edit/index.vue
  client/components/content-elements/tce-html/edit/Toolbar.vue
  client/components/content-elements/tce-true-false/edit/index.vue
  client/main.js
  package-lock.json
  package.json
  packages/core-components/package-lock.json
  packages/core-components/package.json
  packages/core-components/src/components/AssessmentItem.vue
  packages/core-components/src/components/ContainedContent.vue
  packages/core-components/src/components/ContentPreview/Element.vue
  packages/core-components/src/components/ElementList.vue
  poi.config.js
Labels: :point_left: needs code review, :mag: needs QA

#983 :nail_care: Reference DB port in DATABASE_URI
  .env.example
Labels: :bulb: enhancement, :point_left: needs code review

#984 💅 Add "secret" as an example of a AUTH_JWT_SECRET
  .env.example
Labels: :point_left: needs code review

#986 Fix active tab highlight when a subroute is visited on the `repository-info` page
  client/components/repository/index.vue
Labels: :point_left: needs code review

#855 Cypress init
  .env.example
  .gitignore
  client/components/catalog/Add.vue
  client/components/catalog/Card/Tags/index.vue
  client/components/catalog/Card/index.vue
  client/main.js
  client/store/modules/repositories/actions.js
  cypress.config.js
  cypress/.eslintrc.js
  cypress/e2e/auth/sign-in.cy.js
  cypress/e2e/catalog/access-repository.cy.js
  cypress/e2e/catalog/create-repository.cy.js
  cypress/e2e/catalog/repository-tags.cy.js
  cypress/e2e/catalog/search-and-filter.cy.js
  cypress/e2e/catalog/utils.js
  cypress/support/e2e/api.js
  cypress/support/e2e/auth.js
  cypress/support/e2e/common.js
  cypress/support/e2e/index.js
  cypress/support/e2e/repository.js
  cypress/support/e2e/schema.js
  jsconfig.json
  package-lock.json
  package.json
Labels: :construction: work in progress

#968 Fix "reinvite" user action
  server/user/user.controller.js
Labels: :point_left: needs code review, :mag: needs QA

#902 Update publishing component labeling, tooltip and badge
  client/components/repository/Workflow/Overview/index.vue
  client/components/repository/common/Sidebar/Badge.vue
  client/components/repository/common/Sidebar/Publishing.vue
Labels: :point_left: needs code review, :ok_hand: passed QA

#930 Encode filename in source key on Storage#copyFile
  server/shared/storage/providers/amazon.js
Labels: :point_left: needs code review

#1008 Fix color meta label aligment
  client/components/meta-inputs/meta-color/Edit/index.vue
Labels: :ok_hand: passed QA
